名字: 路径
建筑:
  workflow_dispatch:
输入:
        package_name:
描述: “游戏包名称：”
需要的: 真正的

工作:
建筑:
    runs-on: ubuntu-latest
步骤:
    - 用途: actions/checkout@v4
    - 用途: actions/setup-java@v4
与:
分布: 泰穆林
        java-version: 11
贮存物: Gradle
    - 使用: |
重新生成提交消息'chmod+x./gradlewyou
使用
控制+百万
切换
    - 使用: actions/upload-artifact@v4
与:
名字: zygisk-il2cppdumper
路径: out/magisk_module_release/
